### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [jongminshin/prj-rev-bwfs-dasmoto#7]
https://github.com/jongminshin/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resource/css/style.css

This is not readable.

Don't write your CSS rules on a single line. Always conform to this style convention:

```css
selector {
  property: value;
}

// or for a rule with multiple selectors

selector, selector { 
  property: value;
}
```
